@startuml
hide methods
left to right direction

skinparam classAttributeIconSize 0

skinparam class {
    LifeLineBorderColor DodgerBlue
    LifeLineBackgroundColor APPLICATION
    BackgroundColor #D8F5FF
    ArrowColor DodgerBlue
    BorderColor DodgerBlue
}

skinparam packageStyle rectangle

skinparam card {
    LifeLineBorderColor DodgerBlue
    LifeLineBackgroundColor APPLICATION
    BackgroundColor #D8F5FF
    ArrowColor DodgerBlue
    BorderColor DodgerBlue
}


package Users {
    class Username <<Value Object>> {
    +String username
    }

    class Role <<Value Object>> {
    +List<Roles> roles
    }

    class Email <<entity>> <<root>> {
    }

    class FirstName <<Value Object>> {
        +String firstName
        }

    class LastName <<Value Object>> {
        +String lastName
        }

    class FullName <<Value Object>> {
    +String fullName
        }

    class Password <<Value Object>> {
    +String password
    }

}

package Patient {

    class DateOfBirth <<Value Object>> {
    +LocalDate dateOfBirth
    }

    class Gender <<Value Object>> {
    +List<String> genders
    }

    class MedicalRecordNumber <<entity>> <<root>> {
    }

    class EmergencyContact <<Value Object>> {
    +String emergencyContact
    }

    class AllergiesMedicalConditions <<Value Object>> {
    +List<String> allergiesMedicalConditions
    }

    class AppointmentHistory <<Value Object>> {
    +List<Appointment> appointments
    }

}

package Staff{

    class LicenseNumber <<entity>> <<root>> {
    }

    class Specialization <<Value Object>> {
    +String specialization
    }

    class AvailabilitySlots <<Value Object>> {
    +List<LocalDateTime> availabilitySlots
    }

}

package OperationRequest{

    class RequestID <<entity>> <<root>> {
    }

    class DeadlineDate <<Value Object>> {
    +LocalDate deadlineDate
    }

    class Priority <<Value Object>> {
    +String priority
    }

}

package OperationType{

    class TypeID <<entity>> <<root>> {
    }

    class Name <<Value Object>> {
    +String name
    }

    class RequiredStaffBySpecialization <<Value Object>> {
    +Map<String, List<Staff>> requiredStaffBySpecialization
    }

    class EstimatedDuration <<Value Object>> {
    +String estimatedDuration
    }

}

    class PhoneNumber <<entity>>{
    +String phoneNumber
    }


package Appointment{

    class AppointmentID <<entity>> <<root>>{
    }

    class DateAndTime <<Value Object>>{
    +LocalDateTime dateAndTime
    }

    enum AppointmentStatus <<Identity>>{
    +SCHEDULED
    +COMPLETED
    +CANCELLED
    }

}

package SurgeryRoom {

    class RoomNumber <<entity>> <<root>> {
    }

    class Type <<Value Object>> {
    +String roomType
    }

    class Capacity <<Value Object>> {
    +Integer capacity
    }

    class AssignedEquipment <<Value Object>> {
    +List<String> assignedEquipment
    }

    enum RoomStatus <<Identity>> {
    +AVAILABLE
    +OCCUPIED
    +UNDER_MAINTENANCE
    }

    class MaintenanceSlots <<Value Object>> {
    +List<LocalDateTime> maintenanceSlots
    }
}

Email "1" *-> "1" Username: username
Email "1" *-> "1" Role: roles
Email "1" *-> "1" FirstName: firstName
Email "1" *-> "1" LastName: lastName
Email "1" *-> "1" FullName: fullName
Email "1" *--> "1" Password: password

MedicalRecordNumber "1" *-> "1" DateOfBirth: dateOfBirth
MedicalRecordNumber "1" *-> "1" Gender: gender
MedicalRecordNumber "1" *-> "1" EmergencyContact: emergencyContact
MedicalRecordNumber "1" *-> "1" AllergiesMedicalConditions: allergiesMedicalConditions
MedicalRecordNumber "1" *--> "1" AppointmentHistory: appointments

LicenseNumber "1" *-> "1" Specialization: specialization
LicenseNumber "1" *--> "1" AvailabilitySlots: availabilitySlots

RequestID "1" *-> "1" DeadlineDate: deadlineDate
RequestID "1" *--> "1" Priority: priority

TypeID "1" *-> "1" Name: name
TypeID "1" *-> "1" RequiredStaffBySpecialization: requiredStaffBySpecialization
TypeID "1" *--> "1" EstimatedDuration: estimatedDuration

AppointmentID "1" *--> "1" DateAndTime: dateAndTime
AppointmentID "1" *-> "1" AppointmentStatus: status

RoomNumber "1" *-> "1" Type: roomType
RoomNumber "1" *-> "1" Capacity: capacity
RoomNumber "1" *-> "1" AssignedEquipment: assignedEquipment
RoomNumber "1" *-> "1" RoomStatus: status
RoomNumber "1" *--> "1" MaintenanceSlots: maintenanceSlots

MedicalRecordNumber "1" *-> "1" PhoneNumber: phoneNumber
LicenseNumber "1" *-> "1" PhoneNumber: phoneNumber
MedicalRecordNumber "1" *-> "1" Email: email
LicenseNumber "1" *-> "1" Email: email

MedicalRecordNumber "1" *-> "..*" AppointmentID: appointments

RequestID "1" *-> "1" TypeID: type
RequestID "1" *-> "1" MedicalRecordNumber: patient
RequestID "1" *-> "1" LicenseNumber: staff

TypeID "1" *-> "1" LicenseNumber: staff

AppointmentID "1" *-> "1" RoomNumber: room
AppointmentID "1" *-> "1" RequestID: request







@enduml


